[project]
name = 'Time-Dilation-Experience-Sharing-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.experience-records]
path = 'contracts/experience-records.clar'
clarity_version = 2
epoch = 2.5

[contracts.time-dilation-simulations]
path = 'contracts/time-dilation-simulations.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
